openapi: 3.2.0
info:
  title: KORE - Supersim Supersim V1 Sim API
  description: This is the public KORE REST API.
  termsOfService: https://pardot.korewireless.com/koremsa
  contact:
    name: KORE Support
    url: https://korewireless.service-now.com/csm
    email: support@korewireless.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://supersim.api.korewireless.com
security:
- OAuth: []
tags:
- name: SupersimV1Sim
paths:
  /v1/Sims:
    servers:
    - url: https://supersim.api.korewireless.com
    description: Individual IoT Super SIMs
    x-kore:
      defaultOutputProperties:
      - sid
      - unique_name
      - status
      dependentProperties:
        billing_periods:
          mapping:
            sim_sid: sid
          resource_url: /v1/Sims/{sim_sid}/BillingPeriods
        sim_ip_addresses:
          mapping:
            sim_sid: sid
          resource_url: /v1/Sims/{sim_sid}/IpAddresses
      pathType: list
    post:
      summary: Register a Super SIM
      description: Register a Super SIM to your Account
      tags:
      - SupersimV1Sim
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -L -X POST "https://supersim.api.korewireless.com/v1/Sims" --header "Authorization: Bearer <YOUR_AUTH_TOKEN>" --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" --data-urlencode "Iccid=89883070000123456789" --data-urlencode "RegistrationCode=H3LL0W0RLD"

          '
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\nconst data = new URLSearchParams({\n    Iccid: '89883070000123456789',\n    RegistrationCode: 'H3LL0W0RLD'\n  });\nconst response = await fetch('https://supersim.api.korewireless.com/v1/Sims', {\n    method: 'POST',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    },\n    body: data.toString()\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.post(\n    \"https://supersim.api.korewireless.com/v1/Sims\",\n    headers={\n      \"Content-Type\":\"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\n    },\n    data={\n      \"Iccid\":\"89883070000123456789\", \n      \"RegistrationCode\":\"H3LL0W0RLD\"\n    }\n)\nresp = response.json()\nprint(resp)\n"
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supersim.v1.sim'
              examples:
                create:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    unique_name: ''
                    status: new
                    fleet_sid: null
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: Created
      security:
      - OAuth: []
      operationId: CreateSim
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              title: CreateSimRequest
              properties:
                Iccid:
                  type: string
                  description: The [ICCID](https://en.wikipedia.org/wiki/Subscriber_identity_module#ICCID) of the Super SIM to be added to your Account.
                RegistrationCode:
                  type: string
                  description: The 10-digit code required to claim the Super SIM for your Account.
              required:
              - Iccid
              - RegistrationCode
            examples:
              create:
                value:
                  Iccid: '89883070000123456789'
                  RegistrationCode: H3LL0W0RLD
    get:
      summary: List Super SIMs
      description: Retrieve a list of Super SIMs from your account.
      tags:
      - SupersimV1Sim
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -L "https://supersim.api.korewireless.com/v1/Sims" --header "Authorization: Bearer <YOUR_AUTH_TOKEN>"

          '
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\nconst response = await fetch('https://supersim.api.korewireless.com/v1/Sims', {\n    method: 'GET',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    }\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.get(\n  \"https://supersim.api.korewireless.com/v1/Sims\", \n  headers={\n    \"Content-Type\":\"application/x-www-form-urlencoded\",\n    \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n  }\n)\nresp = response.json()\nprint(resp)\n"
      parameters:
      - name: Status
        in: query
        description: The status of the Sim resources to read. Can be `new`, `ready`, `active`, `inactive`, or `scheduled`.
        schema:
          $ref: '#/components/schemas/sim_enum_status'
        examples:
          readEmpty:
            value: new
          readFullByFleetSid:
            value: new
          readFullByFleetName:
            value: new
      - name: Fleet
        in: query
        description: The SID or unique name of the Fleet to which a list of Sims are assigned.
        schema:
          type: string
        examples:
          readEmpty:
            value: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          readFullByFleetSid:
            value: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          readFullByFleetName:
            value: MyFleet
      - name: Iccid
        in: query
        description: The [ICCID](https://en.wikipedia.org/wiki/Subscriber_identity_module#ICCID) associated with a Super SIM to filter the list by. Passing this parameter will always return a list containing zero or one SIMs.
        schema:
          type: string
        x-kore:
          pii:
            handling: standard
            deleteSla: 30
        examples:
          readByIccid:
            value: '89883070000123456789'
      - name: PageSize
        in: query
        description: How many resources to return in each list page. The default is 50, and the maximum is 1000.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: Page
        in: query
        description: The page index. This value is simply for client state.
        schema:
          type: integer
          minimum: 0
      - name: PageToken
        in: query
        description: The page token. This is provided by the API.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  sims:
                    type: array
                    items:
                      $ref: '#/components/schemas/supersim.v1.sim'
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type:
                        - string
                        - 'null'
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type:
                        - string
                        - 'null'
                      url:
                        format: uri
                        type: string
                    type: object
                title: ListSimResponse
              examples:
                readEmpty:
                  value:
                    sims: []
                    meta:
                      first_page_url: https://supersim.api.korewireless.com/v1/Sims?Status=new&Fleet=HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                      key: sims
                      next_page_url: null
                      page: 0
                      page_size: 50
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/Sims?Status=new&Fleet=HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                readFullByFleetSid:
                  value:
                    meta:
                      first_page_url: https://supersim.api.korewireless.com/v1/Sims?Status=new&Fleet=HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                      key: sims
                      next_page_url: null
                      page: 0
                      page_size: 50
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/Sims?Status=new&Fleet=HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                    sims:
                    - sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      unique_name: My SIM
                      status: new
                      fleet_sid: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      iccid: '89883070000123456789'
                      date_created: '2015-07-30T20:00:00Z'
                      date_updated: '2015-07-30T20:00:00Z'
                      url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      links:
                        billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                        sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
                readFullByFleetName:
                  value:
                    meta:
                      first_page_url: https://supersim.api.korewireless.com/v1/Sims?Status=new&Fleet=MyFleet&PageSize=50&Page=0
                      key: sims
                      next_page_url: null
                      page: 0
                      page_size: 50
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/Sims?Status=new&Fleet=MyFleet&PageSize=50&Page=0
                    sims:
                    - sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      unique_name: My SIM
                      status: new
                      fleet_sid: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      iccid: '89883070000123456789'
                      date_created: '2015-07-30T20:00:00Z'
                      date_updated: '2015-07-30T20:00:00Z'
                      url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      links:
                        billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                        sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
                readByIccid:
                  value:
                    meta:
                      first_page_url: https://supersim.api.korewireless.com/v1/Sims?Iccid=89883070000123456789&PageSize=50&Page=0
                      key: sims
                      next_page_url: null
                      page: 0
                      page_size: 50
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/Sims?Iccid=89883070000123456789&PageSize=50&Page=0
                    sims:
                    - sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      unique_name: My SIM
                      status: new
                      fleet_sid: null
                      iccid: '89883070000123456789'
                      date_created: '2015-07-30T20:00:00Z'
                      date_updated: '2015-07-30T20:00:00Z'
                      url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      links:
                        billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                        sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - OAuth: []
      operationId: ListSim
  /v1/Sims/{Sid}:
    servers:
    - url: https://supersim.api.korewireless.com
    description: Individual IoT Super SIMs
    x-kore:
      defaultOutputProperties:
      - sid
      - unique_name
      - status
      dependentProperties:
        billing_periods:
          mapping:
            sim_sid: sid
          resource_url: /v1/Sims/{sim_sid}/BillingPeriods
        sim_ip_addresses:
          mapping:
            sim_sid: sid
          resource_url: /v1/Sims/{sim_sid}/IpAddresses
      pathType: instance
    get:
      summary: Fetch a Super SIM
      description: Fetch a Super SIM instance from your account.
      tags:
      - SupersimV1Sim
      parameters:
      - name: Sid
        in: path
        description: The SID of the Sim resource to fetch.
        schema:
          type: string
        required: true
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: "curl -L \"https://supersim.api.korewireless.com/v1/Sims/{Sid}\" --header \"Authorization: Bearer <YOUR_AUTH_TOKEN>\"   \n"
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\nconst response = await fetch('https://supersim.api.korewireless.com/v1/Sims/<Sid>', {\n    method: 'GET',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    }\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.get(\n  \"https://supersim.api.korewireless.com/v1/Sims/<Sid>\", \n  headers={\n    \"Content-Type\":\"application/x-www-form-urlencoded\",\n    \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n  }\n)\nresp = response.json()\nprint(resp)\n"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supersim.v1.sim'
              examples:
                fetch:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    unique_name: My SIM
                    status: new
                    fleet_sid: null
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - OAuth: []
      operationId: FetchSim
    post:
      summary: Update a SIM
      description: Updates the given properties of a Super SIM instance from your account.
      tags:
      - SupersimV1Sim
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -L -X POST "https://supersim.api.korewireless.com/v1/Sims/<Sid>" --header "Authorization: Bearer <YOUR_AUTH_TOKEN>" --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" --data-urlencode "UniqueName=<NEW_UNIQUE_NAME>" --data-urlencode "CallbackUrl=<YOUR_CALLBACK_URL>" --data-urlencode "CallbackMethod=<GET_OR_POST>"

          '
      - lang: NodeJs
        label: NodeJs
        source: "const https = require('https');\nconst { URLSearchParams } = require('url');\nconst url = \"https://supersim.api.korewireless.com/v1/Sims/<Sid>\";\nconst data = new URLSearchParams({ \n  UniqueName: \"<NEW_UNIQUE_NAME>\", \n  CallbackUrl : \"<YOUR_CALLBACK_URL>\", \n  CallbackMethod : \"<GET_OR_POST>\" }).toString();\nconst options = {\n  method: 'POST',\n  headers: {\n    'Content-Type': 'application/x-www-form-urlencoded',\n    'Content-Length': Buffer.byteLength(data),\n    'Authorization': 'Bearer <YOUR_AUTH_TOKEN>'\n  }\n};\n\nconst req = https.request(url, options, (res) => {\n  let responseData = '';\n  res.on('data', (chunk) => {\n    responseData += chunk;\n  });\n  res.on('end', () => {\n    console.log('Response:', responseData);\n  });\n});\n\nreq.on('error', (error) => {\n  console.error('Error:', error);\n});\n\nreq.write(data);\nreq.end();\n"
      - lang: Python
        label: Python
        source: "import requests\n\nurl = \"https://supersim.api.korewireless.com/v1/Sims/<Sid>\"\ndata = { \n    \"UniqueName\": \"<NEW_UNIQUE_NAME>\", \n    \"CallbackUrl\" : \"<YOUR_CALLBACK_URL>\", \n    \"CallbackMethod\" : \"<GET_OR_POST>\"}\nheaders = {\n    \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"}\nresponse = requests.post(url, data=data, headers=headers)\nif response.status_code == 200:\n    print(response.json())\nelse:\n    print(f\"Error: {response.status_code}, {response.text}\")\n"
      parameters:
      - name: Sid
        in: path
        description: The SID of the Sim resource to update.
        schema:
          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supersim.v1.sim'
              examples:
                updateUniqueName:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    unique_name: MySIM
                    status: new
                    fleet_sid: null
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
                updateFleetWithSid:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    unique_name: null
                    status: new
                    fleet_sid: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
                updateFleetWithUniqueName:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    unique_name: null
                    status: new
                    fleet_sid: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
                transferSimToAnotherAccount:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
                    unique_name: null
                    status: new
                    fleet_sid: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supersim.v1.sim'
              examples:
                updateStatus:
                  value:
                    sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    unique_name: null
                    status: scheduled
                    fleet_sid: null
                    iccid: '89883070000123456789'
                    date_created: '2015-07-30T20:00:00Z'
                    date_updated: '2015-07-30T20:00:00Z'
                    url: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    links:
                      billing_periods: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/BillingPeriods
                      sim_ip_addresses: https://supersim.api.korewireless.com/v1/Sims/HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/IpAddresses
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: Accepted
      security:
      - OAuth: []
      operationId: UpdateSim
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              title: UpdateSimRequest
              properties:
                UniqueName:
                  type: string
                  description: An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.
                Status:
                  $ref: '#/components/schemas/sim_enum_status_update'
                Fleet:
                  type: string
                  description: The SID or unique name of the Fleet to which the SIM resource should be assigned.
                CallbackUrl:
                  type: string
                  format: uri
                  description: The URL we should call using the `callback_method` after an asynchronous update has finished.
                CallbackMethod:
                  type: string
                  format: http-method
                  enum:
                  - GET
                  - POST
                  description: 'The HTTP method we should use to call `callback_url`. Can be: `GET` or `POST` and the default is POST.'
                AccountSid:
                  type: string
                  description: The SID of the Account to which the Sim resource should belong. The Account SID can only be that of the requesting Account or that of a Subaccount of the requesting Account. Only valid when the Sim resource's status is new.
            examples:
              updateUniqueName:
                value:
                  UniqueName: MySIM
              updateStatus:
                value:
                  Status: active
                  CallbackUrl: http://127.0.0.1:9876/path
                  CallbackMethod: POST
              updateFleetWithSid:
                value:
                  Fleet: HFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  CallbackUrl: http://127.0.0.1:9876/path
                  CallbackMethod: POST
              updateFleetWithUniqueName:
                value:
                  Fleet: My Fleet
                  CallbackUrl: http://127.0.0.1:9876/path
                  CallbackMethod: POST
              transferSimToAnotherAccount:
                value:
                  AccountSid: ACbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
                  Fleet: My Fleet
components:
  schemas:
    sim_enum_status_update:
      type: string
      description: 'The new status of the resource. Can be: `ready`, `active`, or `inactive`. See the [Super SIM Status Values](https://docs.korewireless.com/en-us/v/api/products/supersim/sim-resource#status-values) for more info.'
      enum:
      - ready
      - active
      - inactive
    sim_enum_status:
      type:
      - string
      - 'null'
      description: The status of the Super SIM. Can be `new`, `ready`, `active`, `inactive`, or `scheduled`. See the [Super SIM Status Values](https://docs.korewireless.com/en-us/v/api/products/supersim/sim-resource#status-values) for a description of each.
      example: new
      enum:
      - new
      - ready
      - active
      - inactive
      - scheduled
    supersim.v1.sim:
      type: object
      properties:
        sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^HS[0-9a-fA-F]{32}$
          description: The unique string that identifies the Sim resource.
          example: HSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        unique_name:
          type:
          - string
          - 'null'
          description: An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.
          example: My SIM
        account_sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          description: The SID of the [Account](https://docs.korewireless.com/en-us/v/api/global-resources/iam/account) that the Super SIM belongs to.
          example: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        iccid:
          type:
          - string
          - 'null'
          description: The [ICCID](https://en.wikipedia.org/wiki/Subscriber_identity_module#ICCID) associated with the SIM.
          x-kore:
            pii:
              handling: standard
              deleteSla: 30
          example: 89883070000123460000
        status:
          $ref: '#/components/schemas/sim_enum_status'
        fleet_sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^HF[0-9a-fA-F]{32}$
          description: The unique ID of the Fleet configured for this SIM.
          example: null
        date_created:
          type:
          - string
          - 'null'
          format: date-time
          description: The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
          example: '2021-04-01T20:00:00Z'
        date_updated:
          type:
          - string
          - 'null'
          format: date-time
          description: The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
          example: '2021-04-01T20:00:00Z'
        url:
          type:
          - string
          - 'null'
          format: uri
          description: The absolute URL of the Sim Resource.
          example: https://supersim.api.korewireless./v1/Sims/HSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        links:
          type:
          - object
          - 'null'
          format: uri-map
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
    OAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.korewireless.com/api-services/v1/auth/token
          scopes: {}
x-hideTryItPanel: true
x-codeSamples: false
