openapi: 3.2.0
info:
  title: KORE - Supersim Supersim V1 Network Access Profile Network API
  description: This is the public KORE REST API.
  termsOfService: https://pardot.korewireless.com/koremsa
  contact:
    name: KORE Support
    url: https://korewireless.service-now.com/csm
    email: support@korewireless.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://supersim.api.korewireless.com
security:
- OAuth: []
tags:
- name: SupersimV1NetworkAccessProfileNetwork
paths:
  /v1/NetworkAccessProfiles/{NetworkAccessProfileSid}/Networks:
    servers:
    - url: https://supersim.api.korewireless.com
    description: Mobile operator networks which Network Access Profiles allow access to
    x-kore:
      defaultOutputProperties:
      - sid
      parent: /NetworkAccessProfiles/{Sid}
      className: network_access_profile_network
      pathType: list
    get:
      description: Retrieve a list of Network Access Profile resource's Network resource.
      tags:
      - SupersimV1NetworkAccessProfileNetwork
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -L "https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks?Page=1&PageSize=10" --header "Authorization: Bearer <YOUR_AUTH_TOKEN>"

          '
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\n\nconst url = \"https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks\";\nconst params = new URLSearchParams({ Page: \"1\", PageSize: \"1\" });\n\nconst response = await fetch(`${url}?${params.toString()}`, {\n    method: 'GET',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    }\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.get(\n    \"https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks\", \n    headers={\n        \"Content-Type\":\"application/x-www-form-urlencoded\",\n        \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n        },\n    params={\n        \"Page\": \"1\", \"PageSize\": \"1\"\n        }\n)\nresp = response.json()\nprint(resp)\n"
      parameters:
      - name: NetworkAccessProfileSid
        in: path
        description: The unique string that identifies the Network Access Profile resource.
        schema:
          type: string
        required: true
      - name: PageSize
        in: query
        description: How many resources to return in each list page. The default is 50, and the maximum is 1000.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: Page
        in: query
        description: The page index. This value is simply for client state.
        schema:
          type: integer
          minimum: 0
      - name: PageToken
        in: query
        description: The page token. This is provided by the API.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  networks:
                    type: array
                    items:
                      $ref: '#/components/schemas/supersim.v1.network_access_profile.network_access_profile_network'
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type:
                        - string
                        - 'null'
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type:
                        - string
                        - 'null'
                      url:
                        format: uri
                        type: string
                    type: object
                title: ListNetworkAccessProfileNetworkResponse
              examples:
                readFull:
                  value:
                    meta:
                      first_page_url: https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Networks?PageSize=50&Page=0
                      key: networks
                      next_page_url: null
                      page: 0
                      page_size: 50
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Networks?PageSize=50&Page=0
                    networks:
                    - sid: HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      network_access_profile_sid: HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      friendly_name: AT&T
                      iso_country: us
                      identifiers:
                      - mcc: '310'
                        mnc: '410'
                      url: https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Networks/HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - OAuth: []
      operationId: ListNetworkAccessProfileNetwork
    post:
      description: Add a Network resource to the Network Access Profile resource.
      tags:
      - SupersimV1NetworkAccessProfileNetwork
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -X POST "https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<Sid>/Networks" -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Bearer <YOUR_AUTH_TOKEN>" --data-urlencode "Network=<NETWORK_SID>"

          '
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\n\nconst data = new URLSearchParams({\n  \"Network\": \"<NETWORK_SID>\"\n});\nconst response = await fetch('https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks', {\n    method: 'POST',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    },\n    body: data.toString()\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.post(\n    \"https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks\",\n    headers={\n        \"Content-Type\":\"application/x-www-form-urlencoded\",\n        \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    },\n    data={\n        \"Network\": \"<NETWORK_SID>\"\n    }\n)\nresp = response.json()\nprint(resp)\n"
      parameters:
      - name: NetworkAccessProfileSid
        in: path
        description: The unique string that identifies the Network Access Profile resource.
        schema:
          type: string
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supersim.v1.network_access_profile.network_access_profile_network'
              examples:
                create:
                  value:
                    sid: HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    network_access_profile_sid: HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    friendly_name: AT&T
                    iso_country: us
                    identifiers:
                    - mcc: '310'
                      mnc: '410'
                    url: https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Networks/HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: Created
      security:
      - OAuth: []
      operationId: CreateNetworkAccessProfileNetwork
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              title: CreateNetworkAccessProfileNetworkRequest
              properties:
                Network:
                  type: string
                  minLength: 34
                  maxLength: 34
                  pattern: ^HW[0-9a-fA-F]{32}$
                  description: The SID of the Network resource to be added to the Network Access Profile resource.
              required:
              - Network
            examples:
              create:
                value:
                  Network: HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  /v1/NetworkAccessProfiles/{NetworkAccessProfileSid}/Networks/{Sid}:
    servers:
    - url: https://supersim.api.korewireless.com
    description: Mobile operator networks which Network Access Profiles allow access to
    x-kore:
      defaultOutputProperties:
      - sid
      parent: /NetworkAccessProfiles/{Sid}
      className: network_access_profile_network
      pathType: instance
    delete:
      description: Remove a Network resource from the Network Access Profile resource's.
      tags:
      - SupersimV1NetworkAccessProfileNetwork
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -L -X DELETE "https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks/<NETWORK_SID>" --header "Authorization: Bearer <YOUR_AUTH_TOKEN>"

          '
      - lang: NodeJs
        label: NodeJs
        source: "const response = await fetch('https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks/<NETWORK_SID', {\n  method: \"DELETE\",\n  headers: {\n    \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n  }\n});\nconsole.log(response);  \n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.delete(\n    \"https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks/<NETWORK_SID>\",\n    headers={\n        \"Content-Type\":\"application/x-www-form-urlencoded\",\n        \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    }\n)\nif response.status_code == 204:\n    print(\"Network sid deleted successfully from network access profile .\")\nelse:\n    print(f\"Failed to delete network sid from network access profile: {response.status_code} {response.reason}\")\n"
      parameters:
      - name: NetworkAccessProfileSid
        in: path
        description: The unique string that identifies the Network Access Profile resource.
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HA[0-9a-fA-F]{32}$
        required: true
      - name: Sid
        in: path
        description: The SID of the Network resource to be removed from the Network Access Profile resource.
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HW[0-9a-fA-F]{32}$
        required: true
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
      - OAuth: []
      operationId: DeleteNetworkAccessProfileNetwork
    get:
      description: Fetch a Network Access Profile resource's Network resource.
      tags:
      - SupersimV1NetworkAccessProfileNetwork
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -L "https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks/<NETWORK_SID>" --header "Authorization: Bearer <YOUR_AUTH_TOKEN>"

          '
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\nconst response = await fetch('https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks/<NETWORK_SID>', {\n    method: 'GET',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    }\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.get(\n    \"https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/<NETWORK_ACCESS_PROFILE_SID>/Networks/<NETWORK_SID>\", \n    headers={\n            \"Content-Type\":\"application/x-www-form-urlencoded\",\n            \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n            }\n    )\nresp = response.json()\nprint(resp)\n"
      parameters:
      - name: NetworkAccessProfileSid
        in: path
        description: The unique string that identifies the Network Access Profile resource.
        schema:
          type: string
        required: true
      - name: Sid
        in: path
        description: The SID of the Network resource to fetch.
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HW[0-9a-fA-F]{32}$
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supersim.v1.network_access_profile.network_access_profile_network'
              examples:
                fetch:
                  value:
                    sid: HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    network_access_profile_sid: HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    friendly_name: AT&T
                    iso_country: us
                    identifiers:
                    - mcc: '310'
                      mnc: '410'
                    url: https://supersim.api.korewireless.com/v1/NetworkAccessProfiles/HAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Networks/HWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - OAuth: []
      operationId: FetchNetworkAccessProfileNetwork
components:
  schemas:
    supersim.v1.network_access_profile.network_access_profile_network:
      type: object
      properties:
        sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^HW[0-9a-fA-F]{32}$
          description: The unique string that identifies the Network resource.
        network_access_profile_sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^HA[0-9a-fA-F]{32}$
          description: The unique string that identifies the Network resource's Network Access Profile resource.
        friendly_name:
          type:
          - string
          - 'null'
          description: A human readable identifier of the Network this resource refers to.
        iso_country:
          type:
          - string
          - 'null'
          description: The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the Network resource.
        identifiers:
          type:
          - array
          - 'null'
          items: {}
          description: Array of objects identifying the [MCC-MNCs](https://en.wikipedia.org/wiki/Mobile_country_code) that are included in the Network resource.
        url:
          type:
          - string
          - 'null'
          format: uri
          description: The absolute URL of the Network resource.
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
    OAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.korewireless.com/api-services/v1/auth/token
          scopes: {}
x-hideTryItPanel: true
x-codeSamples: false
