openapi: 3.2.0
info:
  title: KORE - Supersim Supersim V1 Settings Update API
  description: This is the public KORE REST API.
  termsOfService: https://pardot.korewireless.com/koremsa
  contact:
    name: KORE Support
    url: https://korewireless.service-now.com/csm
    email: support@korewireless.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://supersim.api.korewireless.com
security:
- OAuth: []
tags:
- name: SupersimV1SettingsUpdate
paths:
  /v1/SettingsUpdates:
    servers:
    - url: https://supersim.api.korewireless.com
    description: ''
    x-kore:
      defaultOutputProperties:
      - sid
      - iccid
      - sim_sid
      - status
      pathType: list
    get:
      description: Retrieve a list of Settings Updates.
      tags:
      - SupersimV1SettingsUpdate
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: "curl -L \"https://supersim.api.korewireless.com/v1/SettingsUpdates?Status=successful&Page=1&PageSize=10\" --header \"Authorization: Bearer <YOUR_AUTH_TOKEN>\" \n"
      - lang: NodeJs
        label: NodeJs
        source: "import { URLSearchParams } from \"url\";\n\nconst url = \"https://supersim.api.korewireless.com/v1/SettingsUpdates\";\nconst params = new URLSearchParams({ Status: \"successful\", Page: \"1\", PageSize: \"10\" });\n\nconst response = await fetch(`${url}?${params.toString()}`, {\n    method: 'GET',\n    headers: {\n      \"Content-Type\": \"application/x-www-form-urlencoded\",\n      \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n    }\n});\nconst resp = await response.json();\nconsole.log(resp);\n"
      - lang: Python
        label: Python
        source: "import requests\n\nresponse = requests.get(\n  \"https://supersim.api.korewireless.com/v1/SettingsUpdates\", \n  headers={\n    \"Content-Type\":\"application/x-www-form-urlencoded\",\n    \"Authorization\": \"Bearer <YOUR_AUTH_TOKEN>\"\n  },\n  params={\n    \"Status\":\"successful\",\n    \"Page\": \"1\", \n    \"PageSize\": \"10\"\n    }\n)\nresp = response.json()\nprint(resp)\n"
      parameters:
      - name: Sim
        in: query
        description: Filter the Settings Updates by a Super SIM's SID or UniqueName.
        schema:
          type: string
        examples:
          readSimOnly:
            value: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          readFull:
            value: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - name: Status
        in: query
        description: Filter the Settings Updates by status. Can be `scheduled`, `in-progress`, `successful`, or `failed`.
        schema:
          $ref: '#/components/schemas/settings_update_enum_status'
        examples:
          readStatusOnly:
            value: scheduled
          readFull:
            value: scheduled
      - name: PageSize
        in: query
        description: How many resources to return in each list page. The default is 50, and the maximum is 1000.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: Page
        in: query
        description: The page index. This value is simply for client state.
        schema:
          type: integer
          minimum: 0
      - name: PageToken
        in: query
        description: The page token. This is provided by the API.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  settings_updates:
                    type: array
                    items:
                      $ref: '#/components/schemas/supersim.v1.settings_update'
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type:
                        - string
                        - 'null'
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type:
                        - string
                        - 'null'
                      url:
                        format: uri
                        type: string
                    type: object
                title: ListSettingsUpdateResponse
              examples:
                readEmpty:
                  value:
                    settings_updates: []
                    meta:
                      page: 0
                      page_size: 50
                      first_page_url: https://supersim.api.korewireless.com/v1/SettingsUpdates?PageSize=50&Page=0
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/SettingsUpdates?PageSize=50&Page=0
                      next_page_url: null
                      key: settings_updates
                readSimOnly:
                  value:
                    settings_updates:
                    - sid: OBaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      iccid: '89883070000123456789'
                      sim_sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      status: successful
                      packages:
                      - name: base-settings
                        version: 1.0.0
                        more_info: https://twilio.com/docs/iot/supersim/settings-packages/base-settings
                      date_completed: '2015-07-30T20:00:00Z'
                      date_created: '2015-07-30T20:00:00Z'
                      date_updated: '2015-07-30T20:00:00Z'
                    meta:
                      page: 0
                      page_size: 50
                      first_page_url: https://supersim.api.korewireless.com/v1/SettingsUpdates?Sim=HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/SettingsUpdates?Sim=HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                      next_page_url: null
                      key: settings_updates
                readStatusOnly:
                  value:
                    settings_updates:
                    - sid: OBaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      iccid: '89883070000123456789'
                      sim_sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      status: scheduled
                      packages:
                      - name: base-settings
                        version: 1.0.0
                        more_info: https://twilio.com/docs/iot/supersim/settings-packages/base-settings
                      date_completed: null
                      date_created: '2015-07-30T20:00:00Z'
                      date_updated: '2015-07-30T20:00:00Z'
                    meta:
                      page: 0
                      page_size: 50
                      first_page_url: https://supersim.api.korewireless.com/v1/SettingsUpdates?Status=scheduled&PageSize=50&Page=0
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/SettingsUpdates?Status=scheduled&PageSize=50&Page=0
                      next_page_url: null
                      key: settings_updates
                readFull:
                  value:
                    settings_updates:
                    - sid: OBaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      iccid: '89883070000123456789'
                      sim_sid: HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      status: scheduled
                      packages:
                      - name: base-settings
                        version: 1.0.0
                        more_info: https://twilio.com/docs/iot/supersim/settings-packages/base-settings
                      date_completed: null
                      date_created: '2015-07-30T20:00:00Z'
                      date_updated: '2015-07-30T20:00:00Z'
                    meta:
                      page: 0
                      page_size: 50
                      first_page_url: https://supersim.api.korewireless.com/v1/SettingsUpdates?Status=scheduled&Sim=HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                      previous_page_url: null
                      url: https://supersim.api.korewireless.com/v1/SettingsUpdates?Status=scheduled&Sim=HSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&PageSize=50&Page=0
                      next_page_url: null
                      key: settings_updates
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - OAuth: []
      operationId: ListSettingsUpdate
components:
  schemas:
    settings_update_enum_status:
      type:
      - string
      - 'null'
      description: The Status of this Settings Update. One of `scheduled`, `in-progress`, `successful` or `failed`.
      enum:
      - scheduled
      - in-progress
      - successful
      - failed
    supersim.v1.settings_update:
      type: object
      properties:
        sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^OB[0-9a-fA-F]{32}$
          description: The unique identifier of this Settings Update.
        iccid:
          type:
          - string
          - 'null'
          description: The [ICCID](https://en.wikipedia.org/wiki/SIM_card#ICCID) associated with the SIM.
        sim_sid:
          type:
          - string
          - 'null'
          minLength: 34
          maxLength: 34
          pattern: ^HS[0-9a-fA-F]{32}$
          description: The SID of the Super SIM to which this Settings Update was applied.
        status:
          $ref: '#/components/schemas/settings_update_enum_status'
        packages:
          type:
          - array
          - 'null'
          items: {}
          description: Array containing the different Settings Packages that will be applied to the SIM after the update completes. Each object within the array indicates the name and the version of the Settings Package that will be on the SIM if the update is successful.
        date_completed:
          type:
          - string
          - 'null'
          format: date-time
          description: The time, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, when the update successfully completed and the new settings were applied to the SIM.
        date_created:
          type:
          - string
          - 'null'
          format: date-time
          description: The date that this Settings Update was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        date_updated:
          type:
          - string
          - 'null'
          format: date-time
          description: The date that this Settings Update was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
    OAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.korewireless.com/api-services/v1/auth/token
          scopes: {}
x-hideTryItPanel: true
x-codeSamples: false
